Repository cloudfoundry/cli, pull requests merged in 2018-11, with the labels that each got.

#1479 Refactor marketplace command
  actor/actionerror/service_not_found_error.go
  actor/sharedaction/check_target.go
  actor/sharedaction/is_logged_in.go
  actor/sharedaction/is_logged_in_test.go
  actor/sharedaction/is_org_targeted.go
  actor/sharedaction/is_org_targeted_test.go
  actor/sharedaction/is_space_targeted.go
  actor/sharedaction/is_space_targeted_test.go
  actor/v2action/cloud_controller_client.go
  actor/v2action/service_summary.go
  actor/v2action/service_summary_test.go
  actor/v2action/v2actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv2/internal/api_routes.go
  api/cloudcontroller/ccv2/service.go
  api/cloudcontroller/ccv2/service_plan.go
  api/cloudcontroller/ccv2/service_plan_test.go
  api/cloudcontroller/ccv2/service_test.go
  command/commandfakes/fake_shared_actor.go
  command/shared_actor.go
  command/v6/marketplace_command.go
  command/v6/marketplace_command_test.go
  command/v6/services_command.go
  command/v6/services_command_test.go
  command/v6/v6fakes/fake_service_instances_actor.go
  command/v6/v6fakes/fake_services_summaries_actor.go
  integration/shared/global/marketplace_command_test.go
  integration/shared/isolated/marketplace_command_test.go
Labels: in progress, sapi

#1487 command/internal/help_common_display_v6: add entry for app delete
  command/common/internal/help_common_display_v6.go
Labels: in progress

#1496 Update Gomega to latest sha
  Gopkg.lock
  vendor/github.com/onsi/gomega/gbytes/say_matcher.go
  vendor/github.com/onsi/gomega/ghttp/handlers.go
  vendor/github.com/onsi/gomega/ghttp/test_server.go
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/gstruct/elements.go
  vendor/github.com/onsi/gomega/gstruct/fields.go
  vendor/github.com/onsi/gomega/internal/assertion/assertion.go
  vendor/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go
  vendor/github.com/onsi/gomega/internal/testingtsupport/testing_t_support.go
  vendor/github.com/onsi/gomega/matchers.go
  vendor/github.com/onsi/gomega/matchers/be_closed_matcher.go
  vendor/github.com/onsi/gomega/matchers/be_numerically_matcher.go
  vendor/github.com/onsi/gomega/matchers/be_sent_matcher.go
  vendor/github.com/onsi/gomega/matchers/match_json_matcher.go
  vendor/github.com/onsi/gomega/matchers/match_yaml_matcher.go
  vendor/github.com/onsi/gomega/matchers/receive_matcher.go
  vendor/github.com/onsi/gomega/matchers/semi_structured_data_support.go
  vendor/github.com/onsi/gomega/matchers/support/goraph/bipartitegraph/bipartitegraph.go
  vendor/github.com/onsi/gomega/matchers/type_support.go
  vendor/github.com/onsi/gomega/types/types.go
Labels: in progress

#1495 Refactor create-service-broker command
  actor/v2action/cloud_controller_client.go
  actor/v2action/service_broker.go
  actor/v2action/service_broker_test.go
  actor/v2action/v2actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv2/internal/api_routes.go
  api/cloudcontroller/ccv2/service_broker.go
  api/cloudcontroller/ccv2/service_broker_test.go
  command/v6/create_service_broker_command.go
  command/v6/create_service_broker_command_test.go
  command/v6/v6fakes/fake_create_service_broker_actor.go
  integration/shared/isolated/create_service_broker_command_test.go
Labels: in progress, sapi

#1502 Enable-service-access refactor
  actor/actionerror/service_plan_not_found_error.go
  actor/v2action/cloud_controller_client.go
  actor/v2action/service.go
  actor/v2action/service_access.go
  actor/v2action/service_access_test.go
  actor/v2action/service_plan.go
  actor/v2action/service_plan_test.go
  actor/v2action/service_test.go
  actor/v2action/v2actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv2/internal/api_routes.go
  api/cloudcontroller/ccv2/service_plan.go
  api/cloudcontroller/ccv2/service_plan_test.go
  api/cloudcontroller/ccv2/service_plan_visibility.go
  api/cloudcontroller/ccv2/service_plan_visibility_test.go
  command/translatableerror/convert_to_translatable_error.go
  command/translatableerror/convert_to_translatable_error_test.go
  command/translatableerror/service_plan_not_found_error.go
  command/v6/enable_service_access_command.go
  command/v6/enable_service_access_command_test.go
  command/v6/v6fakes/fake_enable_service_access_actor.go
  integration/shared/isolated/enable_service_access_command_test.go
Labels: sapi, scheduled

#1507 Handle ServiceBrokerCatalogInvalid errors in CLI
  api/cloudcontroller/ccerror/service_broker_catalog_invalid_error.go
  api/cloudcontroller/ccv2/errors.go
  api/cloudcontroller/ccv2/errors_test.go
Labels: scheduled
