Repository cloudfoundry/cli, pull requests merged in 2018-10, with the labels that each got.

#1470 Add clarifying notes for integration tests
  integration/README.md
Labels: scheduled

#1464 add wait-for-deploy-complete flag to v3-zdt-push
  actor/v3action/cloud_controller_client.go
  actor/v3action/v3actionfakes/fake_cloud_controller_client.go
  actor/v3action/zdt.go
  actor/v3action/zdt_test.go
  api/cloudcontroller/ccerror/deployment_not_found_error.go
  api/cloudcontroller/ccv3/constant/deployment.go
  api/cloudcontroller/ccv3/deployment.go
  api/cloudcontroller/ccv3/deployment_test.go
  api/cloudcontroller/ccv3/errors.go
  api/cloudcontroller/ccv3/internal/api_routes.go
  command/v3/v3_zdt_push_command.go
  command/v3/v3_zdt_push_command_test.go
  command/v3/v3fakes/fake_v3zero_downtime_version_actor.go
  integration/experimental/v3_zdt_push_command_test.go
Labels: scheduled

#1474 add stack flag to v3-zdt-push
  actor/v3action/application.go
  api/cloudcontroller/ccv3/application.go
  api/cloudcontroller/ccv3/application_test.go
  command/v6/v3_zdt_push_command.go
  command/v6/v3_zdt_push_command_test.go
  integration/experimental/v3_zdt_push_command_test.go
Labels: scheduled

#1465 Refactor create-service-key command
  actor/v2action/cloud_controller_client.go
  actor/v2action/service_binding_test.go
  actor/v2action/service_key.go
  actor/v2action/service_key_test.go
  actor/v2action/v2actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccerror/service_key_taken_error.go
  api/cloudcontroller/ccv2/errors.go
  api/cloudcontroller/ccv2/internal/api_routes.go
  api/cloudcontroller/ccv2/service_binding_test.go
  api/cloudcontroller/ccv2/service_key.go
  api/cloudcontroller/ccv2/service_key_test.go
  command/v6/create_service_key_command.go
  command/v6/create_service_key_command_test.go
  command/v6/v6fakes/fake_create_service_key_actor.go
  integration/assets/service_broker/cats.json
  integration/helpers/service_broker.go
  integration/isolated/create_service_key_command_test.go
Labels: sapi, scheduled

#1475 Update Contributing doc
  .github/CONTRIBUTING.md
Labels: unscheduled

#1482 Ensures that cf-deployment and bosh-deployment directories are proper…
  ci/local-integration-env/deploy_bosh_lite.sh
Labels: in progress

#1480 Use CC extra structure for documentation urls
  api/cloudcontroller/ccv2/service.go
  api/cloudcontroller/ccv2/service_extra.go
  api/cloudcontroller/ccv2/service_test.go
  integration/assets/service_broker/cats.json
  integration/shared/global/service_command_test.go
Labels: sapi, scheduled
