Repository cloudfoundry/cli, pull requests merged in 2019-02, with the labels that each got.

#1552 Require a targeted space for delete-service
  cf/commands/service/delete_service.go
  cf/commands/service/delete_service_test.go
  integration/shared/isolated/delete_service_command_test.go
Labels: sapi, scheduled

#1560 Use concise helper to create a service broker
  integration/shared/isolated/enable_service_access_command_test.go
Labels: sapi, unscheduled

#1558 Make enable-service-access command idempotent
  actor/v2action/service_access.go
  actor/v2action/service_access_test.go
  api/cloudcontroller/ccerror/service_plan_visibility_exists_error.go
  api/cloudcontroller/ccv2/errors.go
  api/cloudcontroller/ccv2/errors_test.go
  integration/shared/isolated/enable_service_access_command_test.go
Labels: sapi, unscheduled

#1563 Add -b flag to create-service command
  actor/v2action/service.go
  actor/v2action/service_instance.go
  actor/v2action/service_instance_test.go
  actor/v2action/service_plan.go
  command/v6/create_service_command.go
  command/v6/create_service_command_test.go
  command/v6/v6fakes/fake_create_service_actor.go
  integration/shared/isolated/create_service_command_test.go
Labels: sapi, unscheduled

#1564 Add -b flag to disable-service-access command
  actor/v2action/service.go
  actor/v2action/service_access.go
  actor/v2action/service_access_test.go
  command/v6/disable_service_access_command.go
  command/v6/disable_service_access_command_test.go
  command/v6/v6fakes/fake_disable_service_access_actor.go
  integration/shared/isolated/disable_service_access_command_test.go
Labels: sapi, unscheduled

#1559 Refactor purge-service-offering command
  actor/v2action/cloud_controller_client.go
  actor/v2action/service.go
  actor/v2action/service_test.go
  actor/v2action/v2actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv2/constant/filter.go
  api/cloudcontroller/ccv2/internal/api_routes.go
  api/cloudcontroller/ccv2/service.go
  api/cloudcontroller/ccv2/service_test.go
  api/cloudcontroller/ccversion/maximum_version.go
  command/api_version_warning.go
  command/api_version_warning_test.go
  command/translatableerror/flag_no_longer_supported_error.go
  command/v6/purge_service_offering_command.go
  command/v6/purge_service_offering_command_test.go
  command/v6/v6fakes/fake_purge_service_offering_actor.go
  integration/shared/isolated/purge_service_offering_command_test.go
Labels: sapi, scheduled

#1568 Revert "Add -b flag to purge-service-offering command"
  command/v6/purge_service_offering_command.go
  command/v6/purge_service_offering_command_test.go
  integration/helpers/service_broker.go
  integration/shared/isolated/purge_service_offering_command_test.go
Labels: unscheduled

#1509 Add a PR builder
  ci/bin/reconfigure-pr-builder
  ci/cli-pr-builder/pipeline.yml
  ci/cli-pr-builder/tasks/extract-info-from-pr.yml
  ci/cli-pr-builder/tasks/integration-linux.yml
Labels: in progress

#1569 Add -b flag to purge-service-offering command
  command/v6/purge_service_offering_command.go
  command/v6/purge_service_offering_command_test.go
  integration/helpers/service_broker.go
  integration/shared/isolated/purge_service_offering_command_test.go
Labels: sapi, unscheduled

#1574 Remove global marketplace integration test
  integration/shared/global/marketplace_command_test.go
Labels: unscheduled

#1572 Fix create service by broker for spaceDevelopers
  actor/actionerror/service_and_broker_combination_not_found_error.go
  actor/v2action/service.go
  actor/v2action/service_instance.go
  actor/v2action/service_instance_test.go
  actor/v2action/service_plan.go
  integration/shared/isolated/create_service_command_test.go
Labels: sapi, unscheduled

#1573 Expose '-b' flag in help messages
  actor/actionerror/duplicate_service_error.go
  command/v6/create_service_command.go
  command/v6/disable_service_access_command.go
  command/v6/enable_service_access_command.go
  command/v6/purge_service_offering_command.go
  integration/shared/isolated/create_service_command_test.go
  integration/shared/isolated/disable_service_access_command_test.go
  integration/shared/isolated/enable_service_access_command_test.go
  integration/shared/isolated/purge_service_offering_command_test.go
Labels: sapi, unscheduled

#1577 Allow rename-service when the plan is not visible
  api/cloudcontroller/ccversion/minimum_version.go
  cf/api/resources/service_instances.go
  cf/api/resources/service_instances_test.go
  cf/api/services_test.go
  cf/commands/service/bind_route_service_test.go
  cf/commands/service/service_test.go
  cf/commands/service/services_test.go
  cf/commands/service/update_user_provided_service_test.go
  cf/models/service_instance.go
  cf/models/service_instance_test.go
  integration/shared/isolated/rename_service_command_test.go
Labels: bug, sapi, unscheduled

#1550 Reduce superfluous api requests during update-service command
  cf/actors/planbuilder/plan_builder.go
  cf/actors/planbuilder/plan_builder_test.go
  integration/shared/isolated/update_service_command_test.go
Labels: sapi, unscheduled

#1579 Fix formatting errors
  integration/shared/isolated/update_service_command_test.go
Labels: unscheduled

#1581 Move (most) `cf-service` command tests from global to isolated
  integration/shared/global/service_command_test.go
  integration/shared/isolated/service_command_test.go
Labels: unscheduled
