Repository cloudfoundry/cli, pull requests merged in 2019-01, with the labels that each got.

#1525 Add broker name column in `cf marketplace`
  api/cloudcontroller/ccv2/service.go
  api/cloudcontroller/ccv2/service_test.go
  api/cloudcontroller/ccversion/minimum_version.go
  command/v6/marketplace_command.go
  command/v6/marketplace_command_test.go
  integration/shared/isolated/marketplace_command_test.go
Labels: in progress, sapi

#1527 Refactor disable-service-access command
  actor/v2action/service_access.go
  actor/v2action/service_access_test.go
  command/v6/disable_service_access_command.go
  command/v6/disable_service_access_command_test.go
  command/v6/v6fakes/fake_disable_service_access_actor.go
  integration/shared/isolated/disable_service_access_command_test.go
Labels: in progress, sapi

#1531 Add CreateBroker helper for integration tests
  integration/helpers/service_broker.go
  integration/shared/global/service_command_test.go
  integration/shared/global/share_service_command_test.go
  integration/shared/global/unshare_service_command_test.go
  integration/shared/isolated/bind_service_command_test.go
  integration/shared/isolated/create_service_key_command_test.go
  integration/shared/isolated/delete_service_command_test.go
  integration/shared/isolated/enable_service_access_command_test.go
  integration/shared/isolated/marketplace_command_test.go
  integration/shared/isolated/service_key_command_test.go
  integration/shared/isolated/services_command_test.go
  integration/shared/isolated/unbind_service_command_test.go
  integration/shared/plugin/api_test.go
  integration/v6/push/bind_to_services_in_manifest_test.go
Labels: sapi, scheduled

#1541 Fixing integration cleanup command
  .github/CONTRIBUTING.md
Labels: scheduled

#1542 Support /spaces and /organizations endpoint without guids param
  actor/v3action/organization.go
  actor/v3action/organization_test.go
  actor/v3action/space.go
  actor/v3action/space_test.go
  api/cloudcontroller/ccversion/minimum_version.go
Labels: scheduled

#1532 Extract composite actor for service access
  actor/v2action/composite/composite_suite_test.go
  actor/v2action/composite/compositefakes/fake_broker_actor.go
  actor/v2action/composite/compositefakes/fake_organization_actor.go
  actor/v2action/composite/compositefakes/fake_service_actor.go
  actor/v2action/composite/compositefakes/fake_visibility_actor.go
  actor/v2action/composite/service_broker_summary.go
  actor/v2action/composite/service_broker_summary_test.go
  actor/v2action/service.go
  actor/v2action/service_broker.go
  actor/v2action/service_broker_summary.go
  actor/v2action/service_broker_summary_test.go
  actor/v2action/service_broker_test.go
  actor/v2action/service_plan_visibility.go
  actor/v2action/service_plan_visibility_test.go
  actor/v2action/service_test.go
  command/v6/service_access_command.go
Labels: in progress, sapi

#1538 Include broker name in `cf services` output
  command/v6/services_command.go
  command/v6/services_command_test.go
  integration/shared/isolated/services_command_test.go
Labels: in progress, sapi

#1529 Add -b flag to enable-service-access command
  actor/actionerror/duplicate_service_error.go
  actor/actionerror/service_broker_not_found_error.go
  actor/v2action/service.go
  actor/v2action/service_access.go
  actor/v2action/service_access_test.go
  actor/v2action/service_broker.go
  actor/v2action/service_broker_test.go
  actor/v2action/service_plan.go
  actor/v2action/service_plan_test.go
  actor/v2action/service_test.go
  api/cloudcontroller/ccv2/service.go
  api/cloudcontroller/ccv2/service_test.go
  api/cloudcontroller/ccversion/minimum_version.go
  command/v6/enable_service_access_command.go
  command/v6/enable_service_access_command_test.go
  command/v6/v6fakes/fake_enable_service_access_actor.go
  integration/shared/isolated/enable_service_access_command_test.go
  integration/shared/isolated/marketplace_command_test.go
Labels: in progress, sapi

#1543 Update `delete-orphaned-routes` command to use unmapped routes API
  actor/v2action/cloud_controller_client.go
  actor/v2action/route.go
  actor/v2action/v2actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv2/internal/api_routes.go
  api/cloudcontroller/ccv2/route.go
  command/v6/delete_orphaned_routes_command.go
  command/v6/delete_orphaned_routes_command_test.go
  command/v6/v6fakes/fake_delete_orphaned_routes_actor.go
  integration/shared/isolated/delete_orphaned_routes_command_test.go
Labels: in progress

#1547 Update OIDC ops file for cf-deployment v7
  ci/infrastructure/operations/add-oidc-provider.yml
Labels: scheduled

#1553 Finish refactor of service-access command
  actor/v2action/composite/compositefakes/fake_organization_actor.go
  actor/v2action/composite/compositefakes/fake_service_actor.go
  actor/v2action/composite/service_broker_summary.go
  actor/v2action/composite/service_broker_summary_test.go
  actor/v2action/organization.go
  actor/v2action/organization_test.go
  actor/v2action/service.go
  actor/v2action/service_broker.go
  actor/v2action/service_plan_visibility.go
  actor/v2action/service_test.go
  command/v6/service_access_command.go
  command/v6/service_access_command_test.go
  integration/shared/experimental/service_access_command_test.go
  integration/shared/isolated/disable_service_access_command_test.go
  integration/shared/isolated/service_access_command_test.go
Labels: in progress, sapi

#1536 Handle scenarios of extra org level visibility objects for `enable-service-access` cmd
  actor/v2action/service_access.go
  actor/v2action/service_access_test.go
  integration/shared/isolated/enable_service_access_command_test.go
Labels: bug, in progress, sapi
