Repository cloudfoundry/cli, pull requests merged in 2019-06, with the labels that each got.

#1662 Indicate whether service instances have an upgrade available
  actor/v2action/service_instance_summary.go
  actor/v2action/service_instance_summary_test.go
  api/cloudcontroller/ccv2/service_instance.go
  api/cloudcontroller/ccv2/service_instance_test.go
  api/cloudcontroller/ccv2/space_summary.go
  api/cloudcontroller/ccv2/space_summary_test.go
  api/cloudcontroller/ccversion/minimum_version.go
  command/v6/services_command.go
  command/v6/services_command_test.go
  integration/assets/service_broker/broker_config.json
  integration/helpers/service_broker.go
  integration/shared/isolated/services_command_test.go
Labels: sapi, unscheduled

#1665 Adapt to new credentials format for create broker
  actor/v7action/cloud_controller_client.go
  actor/v7action/service_broker.go
  actor/v7action/service_broker_test.go
  actor/v7action/v7actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv3/constant/service_broker_credentials_type.go
  api/cloudcontroller/ccv3/service_broker.go
  api/cloudcontroller/ccv3/service_broker_test.go
  command/v7/create_service_broker_command.go
  command/v7/create_service_broker_command_test.go
  command/v7/v7fakes/fake_create_service_broker_actor.go
Labels: sapi, unscheduled

#1663 Handle not only comma-separated warnings, but also multi-value header.
  api/cloudcontroller/cloud_controller_connection.go
  api/cloudcontroller/cloud_controller_connection_test.go
Labels: sapi

#1666 Show --upgrade flag as experimental in update-service command
  command/v6/update_service_command.go
  integration/shared/isolated/update_service_command_test.go
Labels: sapi, unscheduled

#1652 Refactor set-label commands to use a shared api layer
  actor/v7action/cloud_controller_client.go
  actor/v7action/label.go
  actor/v7action/label_test.go
  actor/v7action/v7actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv3/metadata.go
  api/cloudcontroller/ccv3/metadata_test.go
Labels: scheduled

#1667 Refactor the service broker helper.
  integration/helpers/fakeservicebroker/configuration.go
  integration/helpers/fakeservicebroker/deployment.go
  integration/helpers/fakeservicebroker/fakeservicebroker.go
  integration/helpers/service_broker.go
  integration/shared/global/service_command_test.go
  integration/shared/global/share_service_command_test.go
  integration/shared/global/unshare_service_command_test.go
  integration/shared/isolated/bind_service_command_test.go
  integration/shared/isolated/create_service_broker_command_test.go
  integration/shared/isolated/create_service_command_test.go
  integration/shared/isolated/create_service_key_command_test.go
  integration/shared/isolated/delete_service_command_test.go
  integration/shared/isolated/disable_service_access_command_test.go
  integration/shared/isolated/enable_service_access_command_test.go
  integration/shared/isolated/marketplace_command_test.go
  integration/shared/isolated/purge_service_offering_command_test.go
  integration/shared/isolated/rename_service_command_test.go
  integration/shared/isolated/service_access_command_test.go
  integration/shared/isolated/service_brokers_command_test.go
  integration/shared/isolated/service_command_test.go
  integration/shared/isolated/service_key_command_test.go
  integration/shared/isolated/services_command_test.go
  integration/shared/isolated/unbind_service_command_test.go
  integration/shared/isolated/update_service_command_test.go
  integration/shared/performance/services_command_performance_test.go
  integration/shared/plugin/api_test.go
  integration/v6/isolated/bind_route_service_command_test.go
  integration/v6/push/bind_to_services_in_manifest_test.go
Labels: sapi, unscheduled

#1668 As a Developer I can see that my CC API version does not support --upgrade
  actor/v2action/composite/compositefakes/fake_get_apiversion_actor.go
  actor/v2action/composite/update_service_instance.go
  actor/v2action/composite/update_service_instance_test.go
  command/v6/update_service_command.go
  command/v6/update_service_command_test.go
  command/v6/v6fakes/fake_update_service_actor.go
  integration/shared/isolated/update_service_command_test.go
Labels: sapi, unscheduled

#1673 Revert "Refactor the service broker helper."
  integration/helpers/fakeservicebroker/configuration.go
  integration/helpers/fakeservicebroker/deployment.go
  integration/helpers/fakeservicebroker/fakeservicebroker.go
  integration/helpers/service_broker.go
  integration/shared/global/service_command_test.go
  integration/shared/global/share_service_command_test.go
  integration/shared/global/unshare_service_command_test.go
  integration/shared/isolated/bind_service_command_test.go
  integration/shared/isolated/create_service_broker_command_test.go
  integration/shared/isolated/create_service_command_test.go
  integration/shared/isolated/create_service_key_command_test.go
  integration/shared/isolated/delete_service_command_test.go
  integration/shared/isolated/disable_service_access_command_test.go
  integration/shared/isolated/enable_service_access_command_test.go
  integration/shared/isolated/marketplace_command_test.go
  integration/shared/isolated/purge_service_offering_command_test.go
  integration/shared/isolated/rename_service_command_test.go
  integration/shared/isolated/service_access_command_test.go
  integration/shared/isolated/service_brokers_command_test.go
  integration/shared/isolated/service_command_test.go
  integration/shared/isolated/service_key_command_test.go
  integration/shared/isolated/services_command_test.go
  integration/shared/isolated/unbind_service_command_test.go
  integration/shared/isolated/update_service_command_test.go
  integration/shared/performance/services_command_performance_test.go
  integration/shared/plugin/api_test.go
  integration/v6/isolated/bind_route_service_command_test.go
  integration/v6/push/bind_to_services_in_manifest_test.go
Labels: unscheduled

#1677 Refactor the service broker helper
  integration/helpers/fakeservicebroker/configuration.go
  integration/helpers/fakeservicebroker/deployment.go
  integration/helpers/fakeservicebroker/fakeservicebroker.go
  integration/helpers/service_broker.go
  integration/shared/global/service_command_test.go
  integration/shared/global/share_service_command_test.go
  integration/shared/global/unshare_service_command_test.go
  integration/shared/isolated/bind_service_command_test.go
  integration/shared/isolated/create_service_broker_command_test.go
  integration/shared/isolated/create_service_command_test.go
  integration/shared/isolated/create_service_key_command_test.go
  integration/shared/isolated/delete_service_command_test.go
  integration/shared/isolated/disable_service_access_command_test.go
  integration/shared/isolated/enable_service_access_command_test.go
  integration/shared/isolated/marketplace_command_test.go
  integration/shared/isolated/purge_service_offering_command_test.go
  integration/shared/isolated/rename_service_command_test.go
  integration/shared/isolated/service_access_command_test.go
  integration/shared/isolated/service_brokers_command_test.go
  integration/shared/isolated/service_command_test.go
  integration/shared/isolated/service_key_command_test.go
  integration/shared/isolated/services_command_test.go
  integration/shared/isolated/unbind_service_command_test.go
  integration/shared/isolated/update_service_command_test.go
  integration/shared/performance/services_command_performance_test.go
  integration/shared/plugin/api_test.go
  integration/v6/isolated/bind_route_service_command_test.go
  integration/v6/push/bind_to_services_in_manifest_test.go
Labels: sapi, unscheduled

#1685 Reuse fake service brokers to improve test speed.
  integration/README.md
  integration/helpers/config.go
  integration/helpers/fakeservicebroker/deployment.go
  integration/helpers/fakeservicebroker/fakeservicebroker.go
  integration/helpers/org_and_space.go
  integration/shared/isolated/create_service_broker_command_test.go
  integration/shared/isolated/create_service_command_test.go
  integration/shared/isolated/disable_service_access_command_test.go
  integration/shared/isolated/enable_service_access_command_test.go
  integration/shared/isolated/isolated_suite_test.go
  integration/shared/isolated/marketplace_command_test.go
  integration/shared/isolated/purge_service_offering_command_test.go
  integration/shared/isolated/service_access_command_test.go
  integration/v6/isolated/bind_route_service_command_test.go
Labels: sapi, unscheduled

#1679 Show the maintenance description in `cf service` output
  actor/v2action/service_instance_summary.go
  actor/v2action/service_instance_summary_test.go
  api/cloudcontroller/ccv2/service_instance.go
  api/cloudcontroller/ccv2/service_plan_test.go
  api/cloudcontroller/ccversion/minimum_version.go
  command/api_version_warning.go
  command/minimum_version_check.go
  command/v6/service_command.go
  command/v6/service_command_test.go
  command/v6/services_command.go
  command/v6/services_command_test.go
  command/v6/v6fakes/fake_service_actor.go
  command/v6/v6fakes/fake_service_instances_actor.go
  integration/helpers/fakeservicebroker/configuration.go
  integration/helpers/fakeservicebroker/fakeservicebroker.go
  integration/shared/isolated/service_command_test.go
  integration/shared/isolated/services_command_test.go
Labels: sapi, unscheduled

#1689 Match timezone abbrs. with more than 3 chars in app_command_test
  integration/v7/isolated/app_command_test.go
Labels: unscheduled

#1639 Remove spinlock in PollStart()
  command/v6/shared/poll_start.go
Labels: accepted

#1703 Make update-service command behaviour consistent when there is no-op
  cf/commands/service/update_service.go
  cf/commands/service/update_service_test.go
  integration/shared/isolated/update_service_command_test.go
Labels: sapi, unscheduled

#1705 Don't send empty version when updating maintenance_info
  api/cloudcontroller/ccv2/service_instance.go
  api/cloudcontroller/ccv2/service_instance_test.go
Labels: unscheduled
