Repository cloudfoundry/cli, pull requests merged in 2019-10, with the labels that each got.

#1804 delete-service-broker v7 implementation
  actor/v7action/cloud_controller_client.go
  actor/v7action/service_broker.go
  actor/v7action/service_broker_test.go
  actor/v7action/v7actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv3/internal/api_routes.go
  api/cloudcontroller/ccv3/service_broker.go
  api/cloudcontroller/ccv3/service_broker_test.go
  command/common/command_list_v7.go
  command/v7/delete_service_broker_command.go
  command/v7/delete_service_broker_command_test.go
  command/v7/v7fakes/fake_delete_service_broker_actor.go
  integration/helpers/fakeservicebroker/defaults.go
  integration/helpers/fakeservicebroker/fakeservicebroker.go
  integration/shared/global/service_command_test.go
  integration/shared/global/share_service_command_test.go
  integration/shared/global/unshare_service_command_test.go
  integration/shared/isolated/bind_service_command_test.go
  integration/shared/isolated/create_service_broker_command_test.go
  integration/shared/isolated/create_service_command_test.go
  integration/shared/isolated/create_service_key_command_test.go
  integration/shared/isolated/delete_service_command_test.go
  integration/shared/isolated/disable_service_access_command_test.go
  integration/shared/isolated/enable_service_access_command_test.go
  integration/shared/isolated/fakeservicebroker_test.go
  integration/shared/isolated/marketplace_command_test.go
  integration/shared/isolated/purge_service_offering_command_test.go
  integration/shared/isolated/rename_service_command_test.go
  integration/shared/isolated/service_access_command_test.go
  integration/shared/isolated/service_brokers_command_test.go
  integration/shared/isolated/service_command_test.go
  integration/shared/isolated/service_key_command_test.go
  integration/shared/isolated/services_command_test.go
  integration/shared/isolated/unbind_service_command_test.go
  integration/shared/isolated/update_service_command_test.go
  integration/shared/performance/services_command_performance_test.go
  integration/shared/plugin/api_test.go
  integration/v6/isolated/bind_route_service_command_test.go
  integration/v6/push/bind_to_services_in_manifest_test.go
  integration/v7/isolated/delete_service_broker_command_test.go
  integration/v7/isolated/space_command_test.go
Labels: sapi, unscheduled

#1807 Add status to service broker struct and output table (V7)
  actor/v7action/service_broker_test.go
  api/cloudcontroller/ccv3/service_broker.go
  api/cloudcontroller/ccv3/service_broker_test.go
  command/v7/service_brokers_command.go
  command/v7/service_brokers_command_test.go
  integration/v6/isolated/service_brokers_command_test.go
  integration/v7/isolated/service_brokers_command_test.go
Labels: sapi, unscheduled

#1811 [V7] delete service broker fails when it has instances
  actor/v7action/cloud_controller_client.go
  actor/v7action/service_broker.go
  actor/v7action/service_broker_test.go
  actor/v7action/v7actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv3/service_broker.go
  api/cloudcontroller/ccv3/service_broker_test.go
  command/v7/delete_service_broker_command.go
  integration/v7/isolated/delete_service_broker_command_test.go
Labels: sapi, unscheduled

#1815 Write shared integration tests for `cf update-service-broker`
  integration/helpers/fakeservicebroker/defaults.go
  integration/helpers/fakeservicebroker/deployment.go
  integration/helpers/fakeservicebroker/fakeservicebroker.go
  integration/shared/isolated/update_service_broker_command_test.go
Labels: sapi, unscheduled

#1824 Implement 'cf update-service-broker' command for V7
  actor/v7action/cloud_controller_client.go
  actor/v7action/service_broker.go
  actor/v7action/service_broker_test.go
  actor/v7action/v7actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv3/internal/api_routes.go
  api/cloudcontroller/ccv3/service_broker.go
  api/cloudcontroller/ccv3/service_broker_test.go
  command/flag/arguments.go
  command/v7/create_service_broker_command.go
  command/v7/delete_service_broker_command.go
  command/v7/update_service_broker_command.go
  command/v7/update_service_broker_command_test.go
  command/v7/v7fakes/fake_update_service_broker_actor.go
  integration/v6/isolated/update_service_broker_command_test.go
  integration/v7/isolated/update_service_broker_command_test.go
Labels: sapi

#1825 Fix flaking compound matcher by replacing it with sequential compound eventual assertions.
  integration/v6/isolated/update_service_broker_command_test.go
  integration/v7/isolated/update_service_broker_command_test.go
Labels: sapi, unscheduled

#1832 Yield processing warnings for pollable jobs as well.
  api/cloudcontroller/ccv3/job.go
  api/cloudcontroller/ccv3/job_test.go
  integration/v7/isolated/update_service_broker_command_test.go
Labels: sapi, unscheduled

#1834 Show TIP about "unknown" status of service brokers in V7.
  command/v7/service_brokers_command.go
  command/v7/service_brokers_command_test.go
  integration/helpers/fakeservicebroker/deployment.go
  integration/helpers/fakeservicebroker/fakeservicebroker.go
  integration/v7/isolated/service_brokers_command_test.go
Labels: sapi, unscheduled

#1817 run-task accepts a process to execute
  api/cloudcontroller/ccv3/task.go
  command/common/command_list_v7.go
  command/flag/arguments.go
  command/v7/run_task_command.go
  command/v7/run_task_command_test.go
  command/v7/v7fakes/fake_run_task_actor.go
Labels: unscheduled
