Repository cloudfoundry/cli, pull requests merged in 2019-05, with the labels that each got.

#1636 Make integration tests less fragile
  integration/shared/isolated/auth_command_test.go
  integration/shared/isolated/restage_command_test.go
  integration/shared/isolated/restart_command_test.go
  integration/shared/isolated/start_command_test.go
  integration/v6/isolated/app_command_test.go
Labels: sapi, unscheduled

#1635 Add experimental --upgrade flag to update-service
  actor/v2action/actor.go
  actor/v2action/cloud_controller_client.go
  actor/v2action/composite/compositefakes/fake_get_service_instance_actor.go
  actor/v2action/composite/compositefakes/fake_get_service_plan_actor.go
  actor/v2action/composite/compositefakes/fake_update_service_instance_maintenance_info_actor.go
  actor/v2action/composite/update_service_instance.go
  actor/v2action/composite/update_service_instance_test.go
  actor/v2action/service_instance.go
  actor/v2action/service_instance_test.go
  actor/v2action/v2actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv2/internal/api_routes.go
  api/cloudcontroller/ccv2/service_instance.go
  api/cloudcontroller/ccv2/service_instance_test.go
  api/cloudcontroller/ccv2/service_plan.go
  api/cloudcontroller/ccv2/service_plan_test.go
  api/cloudcontroller/ccversion/minimum_version.go
  command/v6/update_service_command.go
  command/v6/update_service_command_test.go
  command/v6/v6fakes/fake_update_service_actor.go
  integration/assets/service_broker/broker_config.json
  integration/helpers/service_broker.go
  integration/shared/isolated/update_service_command_test.go
Labels: sapi, unscheduled

#1638 Revert "Add experimental --upgrade flag to update-service"
  actor/v2action/actor.go
  actor/v2action/cloud_controller_client.go
  actor/v2action/composite/compositefakes/fake_get_service_instance_actor.go
  actor/v2action/composite/compositefakes/fake_get_service_plan_actor.go
  actor/v2action/composite/compositefakes/fake_update_service_instance_maintenance_info_actor.go
  actor/v2action/composite/update_service_instance.go
  actor/v2action/composite/update_service_instance_test.go
  actor/v2action/service_instance.go
  actor/v2action/service_instance_test.go
  actor/v2action/v2actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv2/internal/api_routes.go
  api/cloudcontroller/ccv2/service_instance.go
  api/cloudcontroller/ccv2/service_instance_test.go
  api/cloudcontroller/ccv2/service_plan.go
  api/cloudcontroller/ccv2/service_plan_test.go
  api/cloudcontroller/ccversion/minimum_version.go
  command/v6/update_service_command.go
  command/v6/update_service_command_test.go
  command/v6/v6fakes/fake_update_service_actor.go
  integration/assets/service_broker/broker_config.json
  integration/helpers/service_broker.go
  integration/shared/isolated/update_service_command_test.go
Labels: unscheduled

#1634 Update marketplace help with usage for --no-plans
  command/v6/marketplace_command.go
  integration/shared/isolated/marketplace_command_test.go
Labels: sapi, unscheduled

#1633 Dont list disabled plans in cf marketplace
  actor/actionerror/service_broker_not_found_error.go
  actor/v2action/cloud_controller_client.go
  actor/v2action/service_broker.go
  actor/v2action/service_broker_test.go
  actor/v2action/service_summary.go
  actor/v2action/service_summary_test.go
  actor/v2action/v2actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv2/internal/api_routes.go
  api/cloudcontroller/ccv2/service.go
  api/cloudcontroller/ccv2/service_broker.go
  api/cloudcontroller/ccv2/service_broker_test.go
  api/cloudcontroller/ccv2/service_test.go
  command/v6/marketplace_command.go
  command/v6/marketplace_command_test.go
  command/v6/v6fakes/fake_services_summaries_actor.go
  integration/helpers/service_broker.go
  integration/shared/isolated/enable_service_access_command_test.go
  integration/shared/isolated/marketplace_command_test.go
  integration/shared/isolated/purge_service_offering_command_test.go
  integration/shared/isolated/service_access_command_test.go
Labels: sapi, unscheduled

#1642 Revert "Dont list disabled plans in cf marketplace"
  actor/actionerror/service_broker_not_found_error.go
  actor/v2action/cloud_controller_client.go
  actor/v2action/service_broker.go
  actor/v2action/service_broker_test.go
  actor/v2action/service_summary.go
  actor/v2action/service_summary_test.go
  actor/v2action/v2actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv2/internal/api_routes.go
  api/cloudcontroller/ccv2/service.go
  api/cloudcontroller/ccv2/service_broker.go
  api/cloudcontroller/ccv2/service_broker_test.go
  api/cloudcontroller/ccv2/service_test.go
  command/v6/marketplace_command.go
  command/v6/marketplace_command_test.go
  command/v6/v6fakes/fake_services_summaries_actor.go
  integration/helpers/service_broker.go
  integration/shared/isolated/enable_service_access_command_test.go
  integration/shared/isolated/marketplace_command_test.go
  integration/shared/isolated/purge_service_offering_command_test.go
  integration/shared/isolated/service_access_command_test.go
Labels: unscheduled

#1646 Add experimental --upgrade flag to update-service
  actor/v2action/actor.go
  actor/v2action/cloud_controller_client.go
  actor/v2action/composite/compositefakes/fake_get_service_instance_actor.go
  actor/v2action/composite/compositefakes/fake_get_service_plan_actor.go
  actor/v2action/composite/compositefakes/fake_update_service_instance_maintenance_info_actor.go
  actor/v2action/composite/update_service_instance.go
  actor/v2action/composite/update_service_instance_test.go
  actor/v2action/service_instance.go
  actor/v2action/service_instance_test.go
  actor/v2action/v2actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv2/internal/api_routes.go
  api/cloudcontroller/ccv2/service_instance.go
  api/cloudcontroller/ccv2/service_instance_test.go
  api/cloudcontroller/ccv2/service_plan.go
  api/cloudcontroller/ccv2/service_plan_test.go
  api/cloudcontroller/ccversion/minimum_version.go
  command/v6/update_service_command.go
  command/v6/update_service_command_test.go
  command/v6/v6fakes/fake_update_service_actor.go
  integration/assets/service_broker/broker_config.json
  integration/helpers/service_broker.go
  integration/shared/isolated/update_service_command_test.go
Labels: sapi, unscheduled

#1630 Add command for viewing labels for orgs
  actor/v7action/organization.go
  command/v7/labels_command.go
  command/v7/labels_command_test.go
  command/v7/org_command.go
  command/v7/v7fakes/fake_get_label_actor.go
  command/v7/v7fakes/fake_org_actor.go
Labels: in progress

#1651 Implement list service brokers using v3 api
  actor/v7action/cloud_controller_client.go
  actor/v7action/service_broker.go
  actor/v7action/service_broker_test.go
  actor/v7action/v7actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv3/ccv3_suite_test.go
  api/cloudcontroller/ccv3/internal/api_resources.go
  api/cloudcontroller/ccv3/internal/api_routes.go
  api/cloudcontroller/ccv3/service_broker.go
  api/cloudcontroller/ccv3/service_broker_test.go
  command/common/command_list_v7.go
  command/v7/service_brokers_command.go
  command/v7/service_brokers_command_test.go
  command/v7/v7fakes/fake_service_brokers_actor.go
  integration/helpers/service_broker.go
  integration/shared/isolated/service_brokers_command_test.go
Labels: sapi, unscheduled

#1645 ref #117 README - more clearly show `cf login` issue
  README.md
Labels: scheduled

#1649 Add command for viewing labels for space
  actor/v7action/label.go
  command/v7/labels_command.go
  command/v7/labels_command_test.go
  command/v7/v7fakes/fake_labels_actor.go
  integration/v7/isolated/labels_command_test.go
Labels: in progress

#1656 Implement `create-service-broker` commands on V7
  actor/v7action/cloud_controller_client.go
  actor/v7action/service_broker.go
  actor/v7action/service_broker_test.go
  actor/v7action/v7actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv3/internal/api_routes.go
  api/cloudcontroller/ccv3/service_broker.go
  api/cloudcontroller/ccv3/service_broker_test.go
  command/common/command_list_v7.go
  command/v7/create_service_broker_command.go
  command/v7/create_service_broker_command_test.go
  command/v7/v7fakes/fake_create_service_broker_actor.go
  integration/helpers/version_v6.go
  integration/helpers/version_v7.go
  integration/shared/isolated/create_service_broker_command_test.go
Labels: unscheduled

#1660 Integration tests to use helpers to create brokers
  integration/helpers/service_broker.go
  integration/shared/isolated/bind_service_command_test.go
  integration/shared/isolated/create_service_command_test.go
  integration/shared/isolated/rename_service_command_test.go
  integration/shared/isolated/unbind_service_command_test.go
Labels: sapi, unscheduled
