Repository cloudfoundry/cli, pull requests merged in 2020-08, with the labels that each got.

#2013 v8(services): delete service instance using V3 API
  actor/v7action/cloud_controller_client.go
  actor/v7action/service_instance.go
  actor/v7action/service_instance_test.go
  actor/v7action/v7actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv3/internal/api_routes.go
  api/cloudcontroller/ccv3/service_instance.go
  api/cloudcontroller/ccv3/service_instance_test.go
  command/v7/actor.go
  command/v7/delete_service_command.go
  command/v7/delete_service_command_test.go
  command/v7/update_user_provided_service_command_test.go
  command/v7/v7fakes/fake_actor.go
  integration/v7/isolated/delete_service_command_test.go
Labels: delivered

#2015 v8(services): upgrade-service arguments and help
  command/common/command_list_v7.go
  command/v7/upgrade_service_command.go
  command/v7/upgrade_service_command_test.go
  integration/v7/isolated/upgrade_service_command_test.go
Labels: delivered, sapi

#2014 v8(services): v3-update-service validations
  actor/v7action/service_instance.go
  actor/v7action/service_instance_test.go
  command/v7/update_service_command.go
  command/v7/update_service_command_test.go
  integration/v7/isolated/update_service_command_test.go
Labels: delivered, sapi

#2017 v8(services): Update mentions of --upgrade flag to cf upgrade-service command
  command/v7/service_command.go
  command/v7/service_command_test.go
  command/v7/update_service_command.go
  command/v7/update_service_command_test.go
Labels: delivered

#2018 V8 upgrade service command
  actor/actionerror/service_upgrade_not_available_error.go
  actor/v2action/composite/update_service_instance.go
  actor/v2action/composite/update_service_instance_test.go
  actor/v7action/service_instance.go
  actor/v7action/service_instance_test.go
  api/cloudcontroller/ccv3/service_instance_test.go
  command/v6/update_service_command.go
  command/v6/update_service_command_test.go
  command/v7/actor.go
  command/v7/update_service_command.go
  command/v7/update_service_command_test.go
  command/v7/upgrade_service_command.go
  command/v7/upgrade_service_command_test.go
  command/v7/v7fakes/fake_actor.go
  integration/v7/isolated/delete_service_command_test.go
  integration/v7/isolated/upgrade_service_command_test.go
  resources/service_plan_resource.go
  resources/service_plan_resource_test.go
Labels: accepted, sapi

#2019 v8(services): consistently handle whitespaces
  command/flag/arguments.go
  command/v6/service_command.go
  command/v6/service_command_test.go
  command/v6/share_service_command.go
  command/v6/share_service_command_test.go
  command/v6/unshare_service_command.go
  command/v6/unshare_service_command_test.go
  command/v6/update_service_command.go
  command/v6/update_service_command_test.go
  command/v6/update_user_provided_service_command.go
  command/v6/update_user_provided_service_command_test.go
  command/v7/create_service_command.go
  command/v7/create_user_provided_service_command.go
  command/v7/create_user_provided_service_command_test.go
  command/v7/delete_service_command.go
  command/v7/delete_service_command_test.go
  command/v7/rename_service_command.go
  command/v7/service_command.go
  command/v7/service_command_test.go
  command/v7/update_service_command.go
  command/v7/update_service_command_test.go
  command/v7/update_user_provided_service_command.go
  command/v7/update_user_provided_service_command_test.go
  command/v7/upgrade_service_command.go
  command/v7/upgrade_service_command_test.go
  types/trimmed_string.go
  types/trimmed_string_test.go
Labels: delivered, sapi

#2020 V3 update service instance plan
  actor/v2action/composite/update_service_instance.go
  actor/v2action/composite/update_service_instance_test.go
  actor/v7action/service_instance.go
  actor/v7action/service_instance_test.go
  api/cloudcontroller/ccv3/service_instance_test.go
  command/common/command_list_v7.go
  command/v6/v6fakes/fake_update_service_actor.go
  command/v7/actor.go
  command/v7/update_service_command.go
  command/v7/update_service_command_test.go
  command/v7/upgrade_service_command.go
  command/v7/v7fakes/fake_actor.go
  integration/assets/hydrabroker/app/broker.go
  integration/assets/hydrabroker/config/types.go
  integration/assets/hydrabroker/integrationtest/integrationtest_test.go
  integration/helpers/servicebrokerstub/app_config.go
  integration/v7/isolated/update_service_command_test.go
Labels: in progress, sapi

#2025 v8(services): share-service initial setup
  command/common/command_list_v7.go
  command/flag/arguments.go
  command/v7/share_service_command.go
  command/v7/share_service_command_test.go
  integration/v7/isolated/share_service_command_test.go
Labels: delivered

#2027 Validation of orguments for share-service
  actor/v7action/service_instance_sharing.go
  actor/v7action/service_instance_sharing_test.go
  command/v7/actor.go
  command/v7/share_service_command.go
  command/v7/share_service_command_test.go
  command/v7/v7fakes/fake_actor.go
  integration/v7/isolated/share_service_command_test.go
Labels: delivered

#2029 v8(services): v3-unshare-service args, flags and help
  command/common/command_list_v7.go
  command/v7/unshare_service_command.go
  command/v7/unshare_service_command_test.go
  integration/v7/isolated/unshare_service_command_test.go
Labels: delivered, sapi

#2031 V8 share service
  actor/v7action/relationship_list.go
  actor/v7action/relationship_list_test.go
  actor/v7action/service_instance_sharing.go
  actor/v7action/service_instance_sharing_test.go
  command/common/command_list_v7.go
  command/v7/share_service_command.go
  command/v7/share_service_command_test.go
  integration/helpers/org_and_space.go
  integration/v7/global/share_service_command_test.go
  integration/v7/isolated/share_service_command_test.go
Labels: unscheduled

#2036 v8(services): unshare-service validation of params
  actor/v7action/service_instance_sharing.go
  actor/v7action/service_instance_sharing_test.go
  command/flag/arguments.go
  command/v7/actor.go
  command/v7/unshare_service_command.go
  command/v7/unshare_service_command_test.go
  command/v7/v7fakes/fake_actor.go
  integration/v7/isolated/unshare_service_command_test.go
Labels: delivered, sapi
