Repository cloudfoundry/cli, pull requests merged in 2020-06, with the labels that each got.

#1948 Add inactive column to cf m output when looking at a particular offering
  api/cloudcontroller/ccv3/service_plan.go
  api/cloudcontroller/ccv3/service_plan_test.go
  command/v7/marketplace_command.go
  command/v7/marketplace_command_test.go
  integration/v7/isolated/marketplace_command_test.go
Labels: sapi, unscheduled

#1951 refactor: use resources pattern for service instances
  actor/v3action/cloud_controller_client.go
  actor/v3action/service_instance.go
  actor/v3action/service_instance_test.go
  actor/v3action/v3actionfakes/fake_cloud_controller_client.go
  actor/v7action/cloud_controller_client.go
  actor/v7action/service_instance.go
  actor/v7action/service_instance_test.go
  actor/v7action/space_test.go
  actor/v7action/v7actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv3/service_instance.go
  api/cloudcontroller/ccv3/service_instance_test.go
  resources/service_instance_resource.go
  resources/service_instance_resource_test.go
Labels: accepted

#1953 v8: create-user-provided-service should use V3 API
  actor/v7action/cloud_controller_client.go
  actor/v7action/service_instance.go
  actor/v7action/service_instance_test.go
  actor/v7action/v7actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv3/internal/api_routes.go
  api/cloudcontroller/ccv3/service_instance.go
  api/cloudcontroller/ccv3/service_instance_test.go
  command/common/command_list_v7.go
  command/v6/update_user_provided_service_command_test.go
  command/v7/actor.go
  command/v7/create_user_provided_service_command.go
  command/v7/create_user_provided_service_command_test.go
  command/v7/v7fakes/fake_actor.go
  integration/shared/isolated/update_user_provided_service_command_test.go
  integration/v7/isolated/create_user_provided_service_command_test.go
  resources/service_instance_resource.go
  resources/service_instance_resource_test.go
Labels: accepted, sapi

#1965 V8 service command
  actor/v3action/cloud_controller_client.go
  actor/v3action/service_instance.go
  actor/v3action/service_instance_test.go
  actor/v3action/v3actionfakes/fake_cloud_controller_client.go
  actor/v7action/cloud_controller_client.go
  actor/v7action/service_instance.go
  actor/v7action/service_instance_test.go
  actor/v7action/space.go
  actor/v7action/space_test.go
  actor/v7action/v7actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv3/included_resources.go
  api/cloudcontroller/ccv3/paginate.go
  api/cloudcontroller/ccv3/query.go
  api/cloudcontroller/ccv3/requester_test.go
  api/cloudcontroller/ccv3/service_instance.go
  api/cloudcontroller/ccv3/service_instance_test.go
  command/common/command_list_v7.go
  command/v7/actor.go
  command/v7/service_command.go
  command/v7/service_command_test.go
  command/v7/v7fakes/fake_actor.go
  integration/assets/hydrabroker/app/broker.go
  integration/assets/hydrabroker/integrationtest/integrationtest_test.go
  integration/helpers/date.go
  integration/v7/isolated/service_command_test.go
  resources/last_operation_resource.go
  resources/last_operation_resource_test.go
  resources/service_instance_resource.go
  resources/service_instance_resource_test.go
  types/optional_string.go
  types/optional_string_slice.go
  types/optional_string_slice_test.go
  types/optional_string_test.go
Labels: in progress
