Repository cloudfoundry/cli, pull requests merged in 2020-07, with the labels that each got.

#1973 v8(services): cf create-service arguments, flags and help
  command/common/command_list_v7.go
  command/v7/create_service_command.go
  command/v7/create_service_command_test.go
  integration/v7/isolated/create_service_command_test.go
Labels: delivered, sapi

#1980 v8(services): rename service command
  actor/v7action/service_instance.go
  actor/v7action/service_instance_test.go
  command/common/command_list_v7.go
  command/v7/actor.go
  command/v7/rename_service_command.go
  command/v7/rename_service_command_test.go
  command/v7/v7fakes/fake_actor.go
  integration/helpers/service_instance.go
  integration/v6/isolated/service_command_test.go
  integration/v7/isolated/rename_service_command_test.go
Labels: delivered

#1978 v8(services): display parameters in service command
  actor/v7action/cloud_controller_client.go
  actor/v7action/service_instance.go
  actor/v7action/service_instance_test.go
  actor/v7action/v7actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv3/internal/api_routes.go
  api/cloudcontroller/ccv3/service_instance.go
  api/cloudcontroller/ccv3/service_instance_test.go
  command/v7/actor.go
  command/v7/service_command.go
  command/v7/service_command_test.go
  command/v7/v7fakes/fake_actor.go
  integration/assets/hydrabroker/app/broker.go
  integration/assets/hydrabroker/config/types.go
  integration/assets/hydrabroker/integrationtest/integrationtest_test.go
  integration/helpers/servicebrokerstub/app_config.go
  integration/v7/isolated/service_command_test.go
Labels: delivered

#1984 v8(services): introduce railway control structure
  actor/util/railway.go
  actor/util/railway_test.go
  actor/util/util_suite_test.go
  actor/v7action/service_instance.go
Labels: delivered

#1985 v8(services): test - refactor marketplace integration test
  integration/v7/isolated/marketplace_command_test.go
Labels: delivered

#1986 v8(services): add update-service command help
  command/common/command_list_v7.go
  command/v7/update_service_command.go
  command/v7/update_service_command_test.go
  integration/v7/isolated/update_service_command_test.go
Labels: delivered

#1989 v8(services): cf service shows offering tags
  actor/v7action/service_instance.go
  actor/v7action/service_instance_test.go
  command/v7/service_command.go
  integration/assets/hydrabroker/app/broker.go
  integration/assets/hydrabroker/config/types.go
  integration/helpers/servicebrokerstub/app_config.go
  integration/v7/isolated/service_command_test.go
  resources/service_offering_resource.go
  resources/service_offering_resource_test.go
Labels: delivered

#1988 v3(services): refactor: use railway pattern more widely
  actor/railway/railway.go
  actor/railway/railway_suite_test.go
  actor/railway/railway_test.go
  actor/util/railway.go
  actor/util/railway_test.go
  actor/v7action/service_broker.go
  actor/v7action/service_instance.go
  actor/v7action/service_offering.go
Labels: in progress

#1992 v8(services): refactor service command
  actor/v7action/cloud_controller_client.go
  actor/v7action/service_instance.go
  actor/v7action/service_instance_details.go
  actor/v7action/service_instance_details_test.go
  actor/v7action/service_instance_test.go
  actor/v7action/v7actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv3/internal/api_routes.go
  api/cloudcontroller/ccv3/service_offering.go
  api/cloudcontroller/ccv3/service_offering_test.go
  command/v7/service_command.go
  command/v7/service_command_test.go
  integration/v7/isolated/service_command_test.go
  resources/service_instance_resource.go
  resources/service_instance_resource_test.go
  types/optional_boolean.go
  types/optional_boolean_test.go
Labels: in progress

#1995 v8(services): service command displays upgrade info
  actor/v7action/cloud_controller_client.go
  actor/v7action/service_instance_details.go
  actor/v7action/service_instance_details_test.go
  actor/v7action/v7actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccerror/service_plan_not_found_error.go
  api/cloudcontroller/ccv3/internal/api_routes.go
  api/cloudcontroller/ccv3/service_offering.go
  api/cloudcontroller/ccv3/service_offering_test.go
  api/cloudcontroller/ccv3/service_plan.go
  api/cloudcontroller/ccv3/service_plan_test.go
  command/v7/service_command.go
  command/v7/service_command_test.go
  integration/helpers/servicebrokerstub/api.go
  integration/v7/isolated/service_command_test.go
  resources/service_instance_resource.go
  resources/service_instance_resource_test.go
  resources/service_plan_resource.go
  resources/service_plan_resource_test.go
Labels: accepted

#1996 v8(services): update managed service tags
  actor/v7action/service_broker.go
  actor/v7action/service_instance.go
  actor/v7action/service_instance_details.go
  actor/v7action/service_instance_test.go
  actor/v7action/service_offering.go
  command/v7/actor.go
  command/v7/update_service_command.go
  command/v7/update_service_command_test.go
  command/v7/v7fakes/fake_actor.go
  integration/v7/isolated/update_service_command_test.go
  util/railway/railway.go
  util/railway/railway_suite_test.go
  util/railway/railway_test.go
Labels: delivered

#2003 v8(services): correct polling for rename and update
  actor/v7action/service_instance.go
  actor/v7action/service_instance_test.go
  api/cloudcontroller/ccv3/job.go
  api/cloudcontroller/ccv3/job_test.go
Labels: delivered

#2004 v8(services): delete service command help
  command/common/command_list_v7.go
  command/v7/delete_service_command.go
  command/v7/delete_service_command_test.go
  integration/v7/isolated/delete_service_command_test.go
Labels: delivered

#1998 v8(services): service instance parameters can be updated
  actor/v7action/service_instance.go
  actor/v7action/service_instance_test.go
  command/flag/path.go
  command/flag/path_test.go
  command/v6/bind_service_command.go
  command/v6/bind_service_command_test.go
  command/v6/create_service_command.go
  command/v6/create_service_command_test.go
  command/v6/create_service_key_command.go
  command/v6/create_service_key_command_test.go
  command/v7/actor.go
  command/v7/create_service_command.go
  command/v7/create_service_command_test.go
  command/v7/update_service_command.go
  command/v7/update_service_command_test.go
  command/v7/v7fakes/fake_actor.go
  integration/assets/hydrabroker/app/broker.go
  integration/assets/hydrabroker/integrationtest/integrationtest_test.go
  integration/assets/hydrabroker/store/store.go
  integration/v7/isolated/update_service_command_test.go
  resources/service_instance_resource.go
  resources/service_instance_resource_test.go
Labels: delivered

#2005 V8 cf service shows shared from info
  actor/v7action/service_instance_details.go
  actor/v7action/service_instance_details_test.go
  api/cloudcontroller/ccv3/query.go
  command/v7/service_command.go
  command/v7/service_command_test.go
  integration/v7/isolated/service_command_test.go
Labels: delivered

#2010 v8(services): switch service back to old command and namespace new one
  command/common/command_list_v7.go
  integration/v7/isolated/create_service_command_test.go
  integration/v7/isolated/service_command_test.go
  integration/v7/isolated/update_service_command_test.go
Labels: delivered
