Repository cloudfoundry/cli, pull requests merged in 2020-09, with the labels that each got.

#2040 Unshare service instance
  actor/v2v3action/service_instance.go
  actor/v2v3action/service_instance_test.go
  actor/v2v3action/v2v3actionfakes/fake_v3actor.go
  actor/v2v3action/v3_actor.go
  actor/v3action/cloud_controller_client.go
  actor/v3action/relationship_list.go
  actor/v3action/relationship_list_test.go
  actor/v3action/service_instance.go
  actor/v3action/v3actionfakes/fake_cloud_controller_client.go
  actor/v7action/cloud_controller_client.go
  actor/v7action/service_instance.go
  actor/v7action/service_instance_sharing.go
  actor/v7action/service_instance_sharing_test.go
  actor/v7action/service_instance_test.go
  actor/v7action/v7actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv3/relationship.go
  api/cloudcontroller/ccv3/relationship_test.go
  api/cloudcontroller/ccv3/service_instance.go
  api/cloudcontroller/ccv3/service_instance_test.go
  command/common/command_list_v7.go
  command/v6/share_service_command.go
  command/v6/share_service_command_test.go
  command/v6/unshare_service_command.go
  command/v6/unshare_service_command_test.go
  command/v6/v6fakes/fake_share_service_actor.go
  command/v6/v6fakes/fake_unshare_service_actor.go
  command/v7/share_service_command.go
  command/v7/share_service_command_test.go
  command/v7/unshare_service_command.go
  command/v7/unshare_service_command_test.go
  integration/v7/global/unshare_service_command_test.go
  integration/v7/isolated/unshare_service_command_test.go
Labels: delivered

#2045 Remove services old commands
  actor/v2action/composite/update_service_instance.go
  actor/v2action/service_instance.go
  actor/v2action/service_instance_test.go
  actor/v2action/service_instance_user_provided.go
  actor/v2action/service_instance_user_provided_test.go
  command/v6/create_service_command.go
  command/v6/create_service_command_test.go
  command/v6/create_user_provided_service_command.go
  command/v6/delete_service_command.go
  command/v6/purge_service_instance_command.go
  command/v6/rename_service_command.go
  command/v6/update_service_command.go
  command/v6/update_service_command_test.go
  command/v6/update_user_provided_service_command.go
  command/v6/update_user_provided_service_command_test.go
  command/v6/v6fakes/fake_create_service_actor.go
  command/v6/v6fakes/fake_update_service_actor.go
Labels: unscheduled

#2049 v3(services): display command that runs after user has confirmed
  command/v7/delete_service_command.go
  command/v7/delete_service_command_test.go
  command/v7/purge_service_instance_command.go
  command/v7/purge_service_instance_command_test.go
  command/v7/upgrade_service_command.go
  command/v7/upgrade_service_command_test.go
Labels: scheduled

#2054 v8(services): v3-service cmd to show bound apps
  actor/v7action/cloud_controller_client.go
  actor/v7action/service_instance_details.go
  actor/v7action/service_instance_details_test.go
  actor/v7action/service_instance_list.go
  actor/v7action/service_instance_list_test.go
  actor/v7action/v7actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv3/query.go
  api/cloudcontroller/ccv3/service_credential_binding.go
  api/cloudcontroller/ccv3/service_credential_binding_test.go
  command/v7/actor.go
  command/v7/service_command.go
  command/v7/service_command_test.go
  command/v7/v7fakes/fake_actor.go
  resources/service_credential_binding_resource.go
  resources/service_credential_binding_resource_test.go
Labels: in progress

#2055 v8(bindings): only show bound apps in the current space
  actor/v7action/service_instance_list.go
  actor/v7action/service_instance_list_test.go
  api/cloudcontroller/ccv3/service_credential_binding.go
  api/cloudcontroller/ccv3/service_credential_binding_test.go
  integration/v7/isolated/services_command_test.go
  resources/service_credential_binding_resource.go
Labels: delivered, sapi

#2056 v8(services): int test for bindings in service cmd
  command/v7/service_command.go
  command/v7/service_command_test.go
  integration/v7/isolated/service_command_test.go
Labels: delivered

#2058 v(services): missing instance msg quoted name
  command/translatableerror/service_instance_not_found_error.go
  integration/v7/isolated/bind_service_command_test.go
  integration/v7/isolated/create_service_key_command_test.go
  integration/v7/isolated/rename_service_command_test.go
  integration/v7/isolated/share_service_command_test.go
  integration/v7/isolated/unbind_service_command_test.go
  integration/v7/isolated/unshare_service_command_test.go
  integration/v7/isolated/update_service_command_test.go
  integration/v7/isolated/update_user_provided_service_command_test.go
  integration/v7/isolated/upgrade_service_command_test.go
Labels: delivered
