Repository cloudfoundry/cli, pull requests merged in 2020-10, with the labels that each got.

#2060 refactor: labels command newline spacing
  command/v7/labels_command.go
  integration/v7/isolated/labels_command_test.go
Labels: delivered

#2067 v8(services): show status during delete service instance
  actor/v7action/cloud_controller_client.go
  actor/v7action/job.go
  actor/v7action/job_test.go
  actor/v7action/service_instance.go
  actor/v7action/service_instance_test.go
  actor/v7action/v7actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv3/job.go
  api/cloudcontroller/ccv3/job_test.go
  command/v7/actor.go
  command/v7/delete_service_command.go
  command/v7/delete_service_command_test.go
  command/v7/v7fakes/fake_actor.go
  integration/v7/isolated/delete_service_command_test.go
Labels: delivered

#2072 v8(services): add --wait flag to update service
  actor/actionerror/service_instance_update_is_noop.go
  actor/v7action/service_instance.go
  actor/v7action/service_instance_test.go
  command/v7/actor.go
  command/v7/update_service_command.go
  command/v7/update_service_command_test.go
  command/v7/v7fakes/fake_actor.go
  integration/v7/isolated/update_service_command_test.go
Labels: delivered

#2074 v8(services): newline before error create/update/delete
  command/v7/shared/result_waiter.go
Labels: delivered

#2076 v8(create-service): Better error when broker name is required
  actor/actionerror/service_broker_name_required_error.go
  actor/v7action/service_instance.go
  actor/v7action/service_instance_test.go
  integration/v7/isolated/create_service_command_test.go
Labels: delivered, sapi

#2078 v8(services): services-keys using V3 API
  actor/v7action/service_key.go
  actor/v7action/service_key_test.go
  command/common/command_list_v7.go
  command/translatableerror/service_keys_unsupported_user_provided_error.go
  command/v7/actor.go
  command/v7/service_keys_command.go
  command/v7/service_keys_command_test.go
  command/v7/v7fakes/fake_actor.go
  integration/v7/isolated/service_keys_command_test.go
Labels: delivered

#2079 v8(services): help messages refer to service offering
  command/flag/arguments.go
  command/v7/disable_service_access_command.go
  command/v7/enable_service_access_command.go
  command/v7/enable_service_access_command_test.go
  command/v7/purge_service_offering_command.go
  command/v7/service_command.go
  integration/v6/isolated/disable_service_access_command_test.go
  integration/v6/isolated/enable_service_access_command_test.go
  integration/v6/isolated/purge_service_offering_command_test.go
  integration/v7/isolated/disable_service_access_command_test.go
  integration/v7/isolated/enable_service_access_command_test.go
  integration/v7/isolated/purge_service_offering_command_test.go
  integration/v7/isolated/service_command_test.go
Labels: delivered

#2081 v8(services): v3-bind-route-service using V3 API
  actor/v7action/cloud_controller_client.go
  actor/v7action/domain.go
  actor/v7action/route_binding.go
  actor/v7action/route_binding_test.go
  actor/v7action/service_instance.go
  actor/v7action/service_key.go
  actor/v7action/v7actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv3/internal/api_routes.go
  api/cloudcontroller/ccv3/route_binding.go
  api/cloudcontroller/ccv3/route_binding_test.go
  command/common/command_list_v7.go
  command/v7/actor.go
  command/v7/bind_route_service_command.go
  command/v7/bind_route_service_command_test.go
  command/v7/shared/result_waiter.go
  command/v7/update_service_command_test.go
  command/v7/v7_suite_test.go
  command/v7/v7fakes/fake_actor.go
  integration/v7/isolated/bind_route_service_command_test.go
  resources/route_binding.go
  resources/route_binding_test.go
Labels: delivered

#2087 v8(services): tests: sync and async broker responses
  integration/v7/isolated/create_service_command_test.go
  integration/v7/isolated/delete_service_command_test.go
  integration/v7/isolated/update_service_command_test.go
Labels: in progress

#2083 v8(services): refactor update-service actor
  actor/v7action/route_binding.go
  actor/v7action/service_instance.go
  actor/v7action/service_instance_test.go
  actor/v7action/service_key.go
  command/v7/actor.go
  command/v7/create_service_command.go
  command/v7/update_service_command.go
  command/v7/update_service_command_test.go
  command/v7/v7fakes/fake_actor.go
  resources/service_instance_resource.go
Labels: delivered

#2090 v8(services): test: fix hydrabroker fetch binding response
  integration/assets/hydrabroker/app/broker.go
  integration/assets/hydrabroker/app/helpers.go
  integration/assets/hydrabroker/integrationtest/integrationtest_test.go
  integration/assets/hydrabroker/main.go
Labels: scheduled

#2092 v8(services): bind-route-service: get correct route
  actor/v7action/route_binding.go
  actor/v7action/route_binding_test.go
Labels: delivered

#2095 chore: de-duplicate lookup table building
  actor/cfnetworkingaction/policy.go
  actor/v3action/organization.go
  actor/v3action/space.go
  actor/v7action/security_group.go
  actor/v7action/service_instance_list.go
  api/cloudcontroller/ccv3/service_credential_binding.go
  api/cloudcontroller/ccv3/service_instance.go
  api/cloudcontroller/ccv3/service_offering.go
  api/cloudcontroller/ccv3/service_plan.go
  util/lookuptable/lookuptable_suite_test.go
  util/lookuptable/name_from_guid.go
  util/lookuptable/name_from_guid_test.go
  util/lookuptable/resource_from_guid.go
Labels: delivered

#2098 test: bind-route-service --wait flag
  integration/v7/isolated/bind_route_service_command_test.go
Labels: accepted
