Repository cloudfoundry/cli, pull requests merged in 2020-05, with the labels that each got.

#1935 Internals: JSONry should maintain field name case
  api/cloudcontroller/ccv3/service_broker.go
  api/cloudcontroller/ccv3/service_offering.go
  api/cloudcontroller/ccv3/service_plan.go
  api/cloudcontroller/jsonry/jsonry.go
  api/cloudcontroller/jsonry/marshal_test.go
  api/cloudcontroller/jsonry/unmarshal_test.go
Labels: in progress, sapi

#1853 Lowercase hostname for map-route
  cf/commands/route/map_route.go
Labels: unscheduled

#1629 Attempt to translate UAA prompts to user local
  cf/commands/login.go
  i18n/resources/en-us.all.json
  i18n/resources/es-es.all.json
  i18n/resources/i18n_resources.go
Labels: unscheduled

#1939 Consume JSONry as an external library
  Gopkg.lock
  api/cloudcontroller/ccv3/service_broker.go
  api/cloudcontroller/ccv3/service_offering.go
  api/cloudcontroller/ccv3/service_plan.go
  api/cloudcontroller/jsonry/jsonry.go
  api/cloudcontroller/jsonry/jsonry_suite_test.go
  api/cloudcontroller/jsonry/marshal.go
  api/cloudcontroller/jsonry/marshal_test.go
  api/cloudcontroller/jsonry/unmarshal.go
  api/cloudcontroller/jsonry/unmarshal_test.go
  resources/domain_resource.go
  resources/security_group_resource.go
  resources/security_group_resource_test.go
  vendor/code.cloudfoundry.org/jsonry/LICENSE
  vendor/code.cloudfoundry.org/jsonry/errors.go
  vendor/code.cloudfoundry.org/jsonry/inspections.go
  vendor/code.cloudfoundry.org/jsonry/internal/context/context.go
  vendor/code.cloudfoundry.org/jsonry/internal/context/segment.go
  vendor/code.cloudfoundry.org/jsonry/internal/path/path.go
  vendor/code.cloudfoundry.org/jsonry/internal/tree/tree.go
  vendor/code.cloudfoundry.org/jsonry/jsonry.go
  vendor/code.cloudfoundry.org/jsonry/marshal.go
  vendor/code.cloudfoundry.org/jsonry/unmarshal.go
Labels: sapi, unscheduled

#1908 Implement revisions command
  actor/v7action/cloud_controller_client.go
  actor/v7action/revisions.go
  actor/v7action/revisions_test.go
  actor/v7action/v7actionfakes/fake_cloud_controller_client.go
  api/cloudcontroller/ccv3/internal/api_routes.go
  api/cloudcontroller/ccv3/revisions.go
  api/cloudcontroller/ccv3/revisions_test.go
  command/common/command_list_v7.go
  command/common/internal/help_common_display_v7.go
  command/v7/revisions_command.go
  command/v7/revisions_command_test.go
  command/v7/v7fakes/fake_revisions_actor.go
Labels: scheduled
