Repository cloudfoundry/cli, pull requests merged in 2021-03, with the labels that each got.

#2150 cf service: Update headers to make them more consistent
  command/v7/service_command.go
  command/v7/service_command_test.go
  integration/v7/isolated/service_command_test.go
Labels: unscheduled

#2151 v8 service calls only v3 api
  command/common/command_list_v7.go
  command/v6/service_command.go
  command/v6/service_command_test.go
  command/v6/v6fakes/fake_service_actor.go
  integration/v7/isolated/service_command_test.go
Labels: scheduled

#2148 Fix stack being over-ridden everytime in v7 push
  actor/v7pushaction/handle_stack_override.go
  actor/v7pushaction/handle_stack_override_test.go
Labels: unscheduled

#2153 Special chars are not HTML encoded when outputting JSON
  command/commandfakes/fake_ui.go
  command/ui.go
  command/v7/env_command.go
  command/v7/env_command_test.go
  command/v7/security_group_command.go
  util/ui/ui.go
  util/ui/ui_test.go
Labels: delivered

#2154 Use`UI.DisplayJSON` for all services JSON output
  actor/v7action/service_instance_details.go
  actor/v7action/service_instance_details_test.go
  actor/v7action/service_key_test.go
  command/v7/service_command.go
  command/v7/service_command_test.go
  command/v7/service_key_command.go
  command/v7/service_key_command_test.go
  resources/service_credential_binding_details_resource.go
Labels: delivered
