Repository cloudfoundry/cli, pull requests merged in 2021-01, with the labels that each got.

#2126 v7(services): do not poll empty jobs
  api/cloudcontroller/ccv3/job.go
  api/cloudcontroller/ccv3/job_test.go
Labels: delivered

#2125 Add long versions of parameters to scale_command
  command/v7/scale_command.go
Labels: unscheduled

#2129 v8(services): delete-service-key use V3 API
  actor/v7action/service_app_binding_test.go
  actor/v7action/service_key.go
  actor/v7action/service_key_test.go
  command/common/command_list_v7.go
  command/v6/delete_service_key_command.go
  command/v7/actor.go
  command/v7/delete_service_key_command.go
  command/v7/delete_service_key_command_test.go
  command/v7/v7fakes/fake_actor.go
  integration/v7/isolated/delete_service_key_command_test.go
Labels: delivered

#2130 v8(services): create-service-key use V3 API
  actor/v7action/service_key.go
  actor/v7action/service_key_test.go
  api/cloudcontroller/ccv3/errors.go
  api/cloudcontroller/ccv3/errors_test.go
  command/common/command_list_v7.go
  command/v6/create_service_key_command.go
  command/v6/create_service_key_command_test.go
  command/v7/actor.go
  command/v7/bind_route_service_command.go
  command/v7/bind_service_command.go
  command/v7/create_service_command.go
  command/v7/create_service_key_command.go
  command/v7/create_service_key_command_test.go
  command/v7/delete_service_command.go
  command/v7/delete_service_key_command.go
  command/v7/unbind_route_service_command.go
  command/v7/unbind_service_command.go
  command/v7/update_service_command.go
  command/v7/v7fakes/fake_actor.go
  integration/v7/isolated/bind_route_service_command_test.go
  integration/v7/isolated/bind_service_command_test.go
  integration/v7/isolated/create_service_command_test.go
  integration/v7/isolated/create_service_key_command_test.go
  integration/v7/isolated/delete_service_command_test.go
  integration/v7/isolated/delete_service_key_command_test.go
  integration/v7/isolated/unbind_route_service_command_test.go
  integration/v7/isolated/unbind_service_command_test.go
  integration/v7/isolated/update_service_command_test.go
Labels: scheduled
